databases:
  - name: recipe-app
    databaseName: recipe_app_yr1b
    user: recipe_app_yr1b_user

services:
  - type: web
    name: recipe-hub
    runtime: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
